---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iamidentitymappings.iamauthenticator.k8s.aws
spec:
  group: iamauthenticator.k8s.aws
  version: v1alpha1
  scope: Cluster
  names:
    plural: iamidentitymappings
    singular: iamidentitymapping
    kind: IAMIdentityMapping
    categories:
      - all
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          required:
            - userarn
            - username
          properties:
            userarn:
              type: string
            username:
              type: string
            groups:
              type: array
              items:
                type: string
