name: Build and push image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push_to_registries:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Build and push images
      shell: bash
      env:
        VERSION: 0.6.2
      run: python ./build_and_push_images.py --version "$VERSION"
